### ISSUE TITLE
The average precision is decreasing during the training of the network.

### ISSUE THREAD

**Issue by lupeng970504** [tianchenji/PAAD#1]
Hello. You are doing a great job! But I have some doubts in the reproduction process.
The following figure shows why the average precision decreases with the number of training sessions during the network training
![learning_curve](https://user-images.githubusercontent.com/72806069/164894766-b60f71c4-a602-4110-b9aa-140419241399.png)
.

**Comment by tianchenji** [comment]
Hello. We witnessed a similar learning curve as yours. In detail, the average precision kept increasing in the first few epochs and reached the peak around the sixth epoch, after which the metrics started to deteriorate. We hypothesize that the above overfitting is caused by the following two facts:
1.  The ImageCNN is pretrained on visual navigation task, the feature maps generated by which have already been robust and useful enough even before the actual training of PAAD.
2. Some of the anomalous behaviors in the training set are correlated in time, which effectively decreases the size of the training set.

Hope this helps!
